name: CustomObjects
author: JaxkDev
version: 0.0.3
api: [3.9.0]
mcpe-protocol: [361]
main: JaxkDev\CustomObjects\Main
website: "https://github.com/JaxkDev/CustomObjects"
description: "[W.I.P | Pre-Release] PocketMine-MP plugin that brings custom objects to your server !"

commands:
  vehicles:
    description: "CustomObjects general command"
    permission: customobjects.command.use
    usage: /customobjects help
    permission-message: "[CustomObjects] > You do not have permission to use this command."

permissions:
  customobjects:
    default: false
    description: "Toggles all CustomObjects plugin perms."
    children:

      customobjects.command:
        description: "Toggles all CustomObjects commands."
        default: false
        children:
          customobjects.command.spawn:
            description: "Allows user to spawn a object."
            default: op
          customobjects.command.remove:
            description: "Allows user to remove a object."
            default: op
